import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightImageZoom from 'starlight-image-zoom';
import path from 'path';
import { pluginPrivCommand } from './src/lib/ec-priv-command.mjs';
import rehypeContentImageLoading from './plugins/rehype-content-image-loading.mjs';
import remarkInjectPasswordReveal from './plugins/remark-inject-passwordreveal.mjs';
import remarkValidateContentTaxonomy from './plugins/remark-validate-content-taxonomy.mjs';

export default defineConfig({
  site: 'https://idanlab.dev',

  vite: {
    resolve: {
      alias: {
        '@components': path.resolve('./src/components'),
      }
    }
  },

  // Content image loading: a rehype pass sets loading/decoding on content <img> (first eager,
  // rest lazy). Covers raw /public absolute-path images that skip astro:assets. See plugins/.
  // remarkInjectPasswordReveal: a remark pass that auto-injects the PasswordReveal import into
  // any MDX file that uses <PasswordReveal /> inline, so writeups need no per-file import.
  // remarkValidateContentTaxonomy: a read-only remark pass that fails the build on an unknown
  // hand-authored badge/metadata class token or component metadata value (a content typo that would
  // otherwise ship as a silently unstyled element). Runs first so it validates the pristine authored
  // tree; ordering is not otherwise significant since it only reads and never mutates. See plugins/.
  markdown: {
    remarkPlugins: [remarkValidateContentTaxonomy, remarkInjectPasswordReveal],
    rehypePlugins: [rehypeContentImageLoading],
  },

  integrations: [
    starlight({
      expressiveCode: {
        // Chosen by A/B on the busiest bash command lines (Busqueda writeup), not corpus-wide
        // counts: a real command line only exercises a couple of token scopes. tokyo-night is the
        // only-tier dark theme that gives command / flag / IP three distinct colors (github-dark
        // collapsed command+flag+path into one band of blues). one-light separates command vs flag
        // on every command line (catppuccin-latte merged them). Both pass WCAG AA on their code bg.
        themes: ['tokyo-night', 'one-light'],
        // Tag privilege commands (sudo, ...) with .ec-cmd-priv so custom.css can color them
        // distinctly. Implemented as an EC plugin because EC 0.42 rejects Shiki DOM-transformer
        // hooks (span/etc). See src/lib/ec-priv-command.mjs for the mechanism + rationale.
        plugins: [pluginPrivCommand()],
      },
      plugins: [starlightImageZoom()],
      head: [
        // Fonts are self-hosted via @font-face in src/styles/fonts.css (public/fonts/) with
        // metric-matched fallbacks and font-display: swap, so first paint is shift-free with no
        // preload. Font <link rel="preload"> was removed on purpose: Firefox does not credit a
        // same-origin crossorigin font preload served from its own preload cache, so it warned
        // "preloaded but not used" on every page even though both faces paint above the fold. The
        // preload only shortened first-load FOUT (no CLS or LCP effect here). Do not re-add font preloads.
        // Reading-progress bar (styled by #tp-progress in custom.css)
        { tag: 'script', content: "window.addEventListener('DOMContentLoaded',function(){var b=document.createElement('div');b.id='tp-progress';document.body.appendChild(b);var u=function(){var h=document.documentElement,m=h.scrollHeight-h.clientHeight;b.style.width=(m>0?h.scrollTop/m*100:0)+'%';};document.addEventListener('scroll',u,{passive:true});window.addEventListener('resize',u);u();});" },
      ],
      title: "Idan.Lab",
      customCss: ['./src/styles/fonts.css', './src/styles/custom.css'],
      // Additive override: render the default right "On this page" sidebar and add the ToggleAll
      // control at the top (see src/components/overrides/PageSidebar.astro). Default TOC preserved.
      components: {
        PageSidebar: './src/components/overrides/PageSidebar.astro',
        // Additive Footer override: auto-appends the <Principle> coda from frontmatter and suppresses
        // pagination on writeups that carry one (see src/components/overrides/Footer.astro). All other
        // pages render the default footer unchanged.
        Footer: './src/components/overrides/Footer.astro',
      },
      description: 'CTF Writeups, Machine Walkthroughs & Security Notes By Idan Babayan',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/Idan-Babayan' },
      ],
      sidebar: [
        {
          label: 'About',
          link: '/about',
          attrs: { class: 'sb-about' },
        },
        {
          label: 'HackTheBox',
          collapsed: true,
          items: [
            // Manual structure (unlike the autogenerated platforms) must surface the platform
            { label: 'Overview', link: '/hackthebox/' },
            { label: 'Easy', collapsed: true, items: [{ autogenerate: { directory: 'hackthebox/easy' } }] },
            { label: 'Medium', collapsed: true, items: [{ autogenerate: { directory: 'hackthebox/medium' } }] },
            // { label: 'Hard',   collapsed: true, items: [{ autogenerate: { directory: 'hackthebox/hard' } }] },
          ],
        },
        {
          label: 'VulnHub',
          collapsed: true,
          items: [{ autogenerate: { directory: 'vulnhub', collapsed: true } }],
        },
        {
          label: 'PicoCTF',
          collapsed: true,
          items: [{ autogenerate: { directory: 'picoctf', collapsed: true } }],
        },
        {
          label: 'OverTheWire',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/overthewire/' },
            { label: 'Bandit', collapsed: true, items: [{ autogenerate: { directory: 'overthewire/bandit' } }] },
          ],
        },
      ],
    }),
  ],
});
